# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#    inputs:
#      approveDeployment:
#        description: 'Type "approve" to confirm deployment'
#        required: true
#        default: 'pending'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TARGET_SERVICE: targetservice
      CLINICAL_DEPLOY_BRANCHES: "dev stage test"

   

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x ./deploy/clinical/bin/build

      - name: run shell script
        run: ./deploy/clinical/bin/build ravi tripathi TARGET_SERVICE=targetservice

      - name: Conditional Step
        if: contains(env.CLINICAL_DEPLOY_BRANCHES, github.ref_name)
        run: echo "Running on one of the specified branches"
      - name: print environment
        run: echo $CHANGE_TARGET

      - name: print environment
        run: echo $GITHUB_REF


      - name: Set Target Branch as Env Var
        run: echo "TARGET_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV

      - name: print environment
        run: cat $GITHUB_ENV